# Generated by Django 3.0.8 on 2020-08-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
